# Generated by Django 3.0.4 on 2020-03-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('OnlineFloorPass', '0002_auto_20200328_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorpass',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='OnlineFloorPass.Guard'),
        ),
        migrations.AlterField(
            model_name='floorpass',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floorpass',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
