# Generated by Django 3.0.4 on 2020-03-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('OnlineFloorPass', '0003_auto_20200328_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorpass',
            old_name='remarks',
            new_name='purpose',
        ),
        migrations.AddField(
            model_name='guard',
            name='fullname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='fullname',
            field=models.TextField(null=True),
        ),
    ]
