# Generated by Django 3.0.4 on 2020-03-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('OnlineFloorPass', '0004_auto_20200330_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='floorpass',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='floorpass',
            name='time_out',
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logdatetime', models.DateTimeField()),
                ('floorpass',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineFloorPass.FloorPass')),
            ],
        ),
        migrations.AddField(
            model_name='floorpass',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='OnlineFloorPass.Department'),
        ),
        migrations.AddField(
            model_name='floorpass',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='OnlineFloorPass.Location'),
        ),
    ]
