# Generated by Django 3.0.4 on 2020-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('OnlineFloorPass', '0005_auto_20200330_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorpass',
            name='guard',
        ),
        migrations.RemoveField(
            model_name='floorpass',
            name='location',
        ),
        migrations.AddField(
            model_name='log',
            name='guard_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='floorpass',
            name='supervisor',
            field=models.CharField(max_length=4),
        ),
        migrations.DeleteModel(
            name='Guard',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
