# Generated by Django 3.0.4 on 2020-03-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('OnlineFloorPass', '0006_auto_20200331_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorpass',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='OnlineFloorPass.Location'),
        ),
    ]
