# Generated by Django 3.0.4 on 2020-04-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('OnlineFloorPass', '0007_floorpass_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorpass',
            name='status',
            field=models.IntegerField(choices=[(1, 'Stand By'), (2, 'Departed'), (3, 'Arrived')], null=True),
        ),
    ]
