# Generated by Django 3.0.4 on 2020-04-02 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('OnlineFloorPass', '0008_floorpass_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=4, null=True)),
                ('floorpass',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineFloorPass.FloorPass')),
            ],
        ),
    ]
