# Generated by Django 3.0.4 on 2020-04-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('OnlineFloorPass', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_name',
            field=models.TextField(null=True),
        ),
    ]
