# Generated by Django 3.0.4 on 2020-04-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('OnlineFloorPass', '0010_user_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorpass',
            name='supervisor',
            field=models.TextField(),
        ),
    ]
