# Generated by Django 3.0.4 on 2020-04-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('OnlineFloorPass', '0011_auto_20200403_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorpass',
            name='latest_log_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
