# Generated by Django 3.0.4 on 2020-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFloorPass', '0012_floorpass_latest_log_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorpass',
            name='employee_ids',
        ),
        migrations.RemoveField(
            model_name='floorpass',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='floorpass',
            name='supervisor_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='floorpass',
            name='supervisor_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
