# Generated by Django 3.0.4 on 2020-04-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFloorPass', '0014_auto_20200430_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorpass',
            name='latest_log_date',
        ),
    ]
